# Nazwa workflow, która będzie widoczna w zakładce "Actions" na GitHubie
name: Build and Deploy .NET API to Azure

# Konfiguracja triggera (wyzwalacza)
on:
  push:
    branches:
      - main  # Uruchom workflow po każdym push na gałąź main
  workflow_dispatch: # Umożliwia ręczne uruchomienie workflow z interfejsu GitHub

# Definicja zmiennych środowiskowych
env:
  AZURE_WEBAPP_NAME: bartek-ecommerceapi-d0h5dcgfdzephvgt  # Twoja nazwa aplikacji z Azure
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'ECommerceApi.csproj'

jobs:
  # --- ZADANIE 1: ETAP BUDOWANIA APLIKACJI ---
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish

    # Krok kluczowy: Zapisujemy wynik budowania (folder ./publish) jako artefakt
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./publish

  # --- ZADANIE 2: ETAP AUTOMATYCZNEGO WDROŻENIA W AZURE ---
  deploy:
    # To zadanie uruchomi się tylko wtedy, gdy zadanie 'build' zakończy się sukcesem
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Krok kluczowy: Pobieramy artefakt stworzony w zadaniu 'build'
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ./publish # Rozpakuj do folderu ./publish

    # Wdrażamy zawartość artefaktu na Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.bartek-ecommerceapi-d0h5dcgfdzephvgt }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'